//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CD()
        {
            this.UserRentedCDs = new HashSet<UserRentedCD>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Publisher { get; set; }
        public string Genre { get; set; }
        public string Artist { get; set; }
        public string Composer { get; set; }
        public string Language { get; set; }
        public string GameMode { get; set; }
        public string Developer { get; set; }
        public int CDTypeId { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> TotalCD { get; set; }
        public Nullable<int> CDLeft { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool IsDeleted { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual CDType CDType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRentedCD> UserRentedCDs { get; set; }
    }
}
