//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipToUser
    {
        public int Id { get; set; }
        public string MembershipNumber { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> MembershipTypeId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateExpired { get; set; }
        public Nullable<bool> IsRequested { get; set; }
        public Nullable<bool> IsExpired { get; set; }
    
        public virtual MembershipType MembershipType { get; set; }
        public virtual User User { get; set; }
    }
}
